version: "3"

services:
  backend:
    image: strapi/strapi
    container_name: strapi_api
    working_dir: "/app/backend"
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    # command: npm run dockerbuild
    networks:
      - strapi-app-network
    volumes:
      - ./backend:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - mongo_db

  frontend:
    image: node:latest
    container_name: website
    working_dir: "/app/frontend"
    restart: unless-stopped
    env_file: .env
    command: yarn dev
    networks:
      - strapi-app-network
    environment:
      - API_BASEURL=${API_BASEURL}
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - backend

  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/data/db
    ports:
      - "27017:27017"

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:
